name: Use TK Automation

on:
  push:
    branches:
      - main

jobs:
  call_external_workflow:
    uses: rjtests/taktile-automation/.github/workflows/send_code.yml@main
    with:
      ORG_NAME: "NB36"
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
